#!/usr/bin/env bash

set -x

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

declare -A gaps
declare -A color

color["focused"]="0xFF40FF00"
color["normal"]="0xff555555"
color["preselect"]="0xE02d74da"

# ===== Tiling setting =========================

yabai -m config layout                      bsp
yabai -m config --space 1 layout stack

yabai -m config top_padding                 0
yabai -m config bottom_padding              0
yabai -m config left_padding                36
yabai -m config right_padding               36
yabai -m config window_gap                  0

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               on

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "${color["focused"]}"
# yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

# yabai -m config active_window_opacity       1.0
# yabai -m config normal_window_opacity       0.90
# yabai -m config split_ratio                 0.50

# yabai -m config auto_balance                off

# yabai -m config mouse_modifier              fn
# yabai -m config mouse_action1               move
# yabai -m config mouse_action2               resize

# ==== Signals ========================

yabai -m signal --add event=window_created action="~/.bin/window_created"
yabai -m signal --add event=application_activated action="~/.bin/window_created"

# # ===== Space setting =========================

# # Space labels
yabai -m space 1 --label "Work"
yabai -m space 2 --label "Comms"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Media"

 # Unmanaged
yabai -m rule --add app="Finder"                manage=off border=off  sticky=on
yabai -m rule --add app="^Hammerspoon"                manage=off border=off layer=above
yabai -m rule --add app="Wally"                manage=off border=off layer=above
yabai -m rule --add app="^1Password 7$"             manage=off border=off
yabai -m rule --add title="^1Password"             manage=off border=off sticky=on layer=above
yabai -m rule --add app="Dictionary"             manage=off border=off sticky=on layer=above
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="Dash" manage=off layer=above sticky=on
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add title="^Accessibility Access$" manage=off layer=above sticky=on
yabai -m rule --add app="Google Chrome" title="MetaMask Notification" manage=off layer=above sticky=on
yabai -m rule --add app="Google Chrome" title="Keplr" manage=off layer=above sticky=on
yabai -m rule --add app="Brave Browser" title="MetaMask Notification" manage=off layer=above sticky=on
yabai -m rule --add app="Brave Browser" title="Keplr" manage=off layer=above sticky=on
yabai -m rule --add title="^ExpressVPN" manage=off layer=above sticky=on
yabai -m rule --add title="^Keplr" manage=off layer=above sticky=on
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Color Picker" manage=off sticky=on layer=above
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^Archive Utility$' manage=off
yabai -m rule --add app="Preview" manage=off 


# # Primary
yabai -m rule --add app="Brave Browser"         space=1
yabai -m rule --add app="Google Chrome"         space=1
yabai -m rule --add app="Safari"         space=1
yabai -m rule --add app="Firefox"         space=1
yabai -m rule --add app="Simulator"             space=1
yabai -m rule --add app="Visual Studio Code"                  space=1
yabai -m rule --add app="Xcode"                  space=1
yabai -m rule --add app="iTerm"                  space=1 border=off
yabai -m rule --add app="zoom.us"              space=1
yabai -m rule --add app="Fantastical"               space=3

# # Communication
yabai -m rule --add app="Slack"                 space=2
yabai -m rule --add app="Spark"                 space=2
yabai -m rule --add app="Messages"              space=2
yabai -m rule --add app="Zoom"              space=2

# # Tools
yabai -m rule --add app="Activity Monitor"      space=3
yabai -m rule --add app="App Store"             space=3
yabai -m rule --add app="Postico"               space=3
yabai -m rule --add app="Things"                  space=3

# Social
yabai -m rule --add app="Discord"               space=4
yabai -m rule --add app="WhatsApp"              space=4
yabai -m rule --add app="Telegram"              space=4
yabai -m rule --add app="Discord"              space=4
yabai -m rule --add app="Opera"              space=4

# Media
yabai -m rule --add app="QuickTime Player"      space=5
yabai -m rule --add app="VLC"                   space=5
yabai -m rule --add app="Spotify"               space=5
