// Generated by executor. Do not edit by hand.
// Source: linear (src_9d2afca7-3234-440d-90ca-6365561e7e84)

type LinearGetDocumentCall = {
  id: string;
};
type LinearGetTeamCall = {
  query: string;
};
type LinearGetTeamResult = {
  data: LinearGetTeamResultData;
  error: LinearGetTeamResultData;
  headers: LinearGetTeamResultHeaders;
  status: null;
};
type LinearGetTeamResultData = unknown | null;
type LinearGetTeamResultHeaders = {
  [key: string]: string;
};
type LinearListIssuesCallAssignee = string | null;
type SaveInitiativeCallParentInitiatives = Array<string>;

export interface SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84 {
  linear: {
    create_attachment: (args: {
  base64Content: string;
  contentType: string;
  filename: string;
  issue: string;
  subtitle?: string;
  title?: string;
}) => Promise<LinearGetTeamResult>;
    create_document: (args: {
  color?: string;
  content?: string;
  icon?: string;
  issue?: string;
  project?: string;
  title: string;
}) => Promise<LinearGetTeamResult>;
    create_issue_label: (args: {
  color?: string;
  description?: string;
  isGroup?: boolean;
  name: string;
  parent?: string;
  teamId?: string;
}) => Promise<LinearGetTeamResult>;
    delete_attachment: (args: LinearGetDocumentCall) => Promise<LinearGetTeamResult>;
    delete_comment: (args: LinearGetDocumentCall) => Promise<LinearGetTeamResult>;
    delete_status_update: (args: {
  id: string;
  type: "initiative";
}) => Promise<LinearGetTeamResult>;
    extract_images: (args: {
  markdown: string;
}) => Promise<LinearGetTeamResult>;
    get_attachment: (args: LinearGetDocumentCall) => Promise<LinearGetTeamResult>;
    get_document: (args: LinearGetDocumentCall) => Promise<LinearGetTeamResult>;
    get_initiative: (args: {
  includeProjects?: boolean;
  includeSubInitiatives?: boolean;
  query: string;
}) => Promise<LinearGetTeamResult>;
    get_issue: (args: {
  id: string;
  includeCustomerNeeds?: boolean;
  includeRelations?: boolean;
}) => Promise<LinearGetTeamResult>;
    get_issue_status: (args: {
  id: string;
  name: string;
  team: string;
}) => Promise<LinearGetTeamResult>;
    get_milestone: (args: {
  project: string;
  query: string;
}) => Promise<LinearGetTeamResult>;
    get_project: (args: {
  includeMembers?: boolean;
  includeMilestones?: boolean;
  includeResources?: boolean;
  query: string;
}) => Promise<LinearGetTeamResult>;
    get_status_updates: (args: {
  createdAt?: string;
  cursor?: string;
  id?: string;
  includeArchived?: boolean;
  initiative?: string;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  project?: string;
  type: "initiative";
  updatedAt?: string;
  user?: string;
}) => Promise<LinearGetTeamResult>;
    get_team: (args: LinearGetTeamCall) => Promise<LinearGetTeamResult>;
    get_user: (args: LinearGetTeamCall) => Promise<LinearGetTeamResult>;
    list_comments: (args: {
  cursor?: string;
  issueId: string;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
}) => Promise<LinearGetTeamResult>;
    list_cycles: (args: {
  teamId: string;
  type?: "current" | "previous" | "next";
}) => Promise<LinearGetTeamResult>;
    list_documents: (args?: {
  createdAt?: string;
  creatorId?: string;
  cursor?: string;
  includeArchived?: boolean;
  initiativeId?: string;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  projectId?: string;
  query?: string;
  updatedAt?: string;
}) => Promise<LinearGetTeamResult>;
    list_initiatives: (args?: {
  createdAt?: string;
  cursor?: string;
  includeArchived?: boolean;
  includeProjects?: boolean;
  includeSubInitiatives?: boolean;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  owner?: string;
  parentInitiative?: string;
  query?: string;
  status?: string;
  updatedAt?: string;
}) => Promise<LinearGetTeamResult>;
    list_issue_labels: (args?: {
  cursor?: string;
  limit?: number;
  name?: string;
  orderBy?: "createdAt" | "updatedAt";
  team?: string;
}) => Promise<LinearGetTeamResult>;
    list_issue_statuses: (args: {
  team: string;
}) => Promise<LinearGetTeamResult>;
    list_issues: (args?: {
  assignee?: LinearListIssuesCallAssignee;
  createdAt?: string;
  cursor?: string;
  cycle?: string;
  delegate?: string;
  includeArchived?: boolean;
  label?: string;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  parentId?: string;
  priority?: number;
  project?: string;
  query?: string;
  state?: string;
  team?: string;
  updatedAt?: string;
}) => Promise<LinearGetTeamResult>;
    list_milestones: (args: {
  project: string;
}) => Promise<LinearGetTeamResult>;
    list_project_labels: (args?: {
  cursor?: string;
  limit?: number;
  name?: string;
  orderBy?: "createdAt" | "updatedAt";
}) => Promise<LinearGetTeamResult>;
    list_projects: (args?: {
  createdAt?: string;
  cursor?: string;
  includeArchived?: boolean;
  includeMembers?: boolean;
  includeMilestones?: boolean;
  initiative?: string;
  label?: string;
  limit?: number;
  member?: string;
  orderBy?: "createdAt" | "updatedAt";
  query?: string;
  state?: string;
  team?: string;
  updatedAt?: string;
}) => Promise<LinearGetTeamResult>;
    list_teams: (args?: {
  createdAt?: string;
  cursor?: string;
  includeArchived?: boolean;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  query?: string;
  updatedAt?: string;
}) => Promise<LinearGetTeamResult>;
    list_users: (args?: {
  cursor?: string;
  limit?: number;
  orderBy?: "createdAt" | "updatedAt";
  query?: string;
  team?: string;
}) => Promise<LinearGetTeamResult>;
    save_comment: (args: {
  body: string;
  id?: string;
  issueId?: string;
  parentId?: string;
}) => Promise<LinearGetTeamResult>;
    save_initiative: (args?: {
  color?: string;
  description?: string;
  icon?: string;
  id?: string;
  name?: string;
  owner?: LinearListIssuesCallAssignee;
  parentInitiatives?: SaveInitiativeCallParentInitiatives;
  status?: string;
  summary?: string;
  targetDate?: string;
}) => Promise<LinearGetTeamResult>;
    save_issue: (args?: {
  assignee?: LinearListIssuesCallAssignee;
  blockedBy?: SaveInitiativeCallParentInitiatives;
  blocks?: SaveInitiativeCallParentInitiatives;
  cycle?: string;
  delegate?: LinearListIssuesCallAssignee;
  description?: string;
  dueDate?: string;
  duplicateOf?: LinearListIssuesCallAssignee;
  estimate?: number;
  id?: string;
  labels?: SaveInitiativeCallParentInitiatives;
  links?: Array<{
  title: string;
  url: string;
}>;
  milestone?: string;
  parentId?: LinearListIssuesCallAssignee;
  priority?: number;
  project?: string;
  relatedTo?: SaveInitiativeCallParentInitiatives;
  state?: string;
  team?: string;
  title?: string;
}) => Promise<LinearGetTeamResult>;
    save_milestone: (args: {
  description?: string;
  id?: string;
  name?: string;
  project: string;
  targetDate?: LinearListIssuesCallAssignee;
}) => Promise<LinearGetTeamResult>;
    save_project: (args?: {
  addInitiatives?: SaveInitiativeCallParentInitiatives;
  addTeams?: SaveInitiativeCallParentInitiatives;
  color?: string;
  description?: string;
  icon?: string;
  id?: string;
  labels?: SaveInitiativeCallParentInitiatives;
  lead?: LinearListIssuesCallAssignee;
  name?: string;
  priority?: number;
  removeInitiatives?: SaveInitiativeCallParentInitiatives;
  removeTeams?: SaveInitiativeCallParentInitiatives;
  setInitiatives?: SaveInitiativeCallParentInitiatives;
  setTeams?: SaveInitiativeCallParentInitiatives;
  startDate?: string;
  state?: string;
  summary?: string;
  targetDate?: string;
}) => Promise<LinearGetTeamResult>;
    save_status_update: (args: {
  body?: string;
  health?: "onTrack" | "atRisk" | "offTrack";
  id?: string;
  initiative?: string;
  isDiffHidden?: boolean;
  project?: string;
  type: "initiative";
}) => Promise<LinearGetTeamResult>;
    search_documentation: (args: {
  page?: number;
  query: string;
}) => Promise<LinearGetTeamResult>;
    update_document: (args: {
  color?: string;
  content?: string;
  icon?: string;
  id: string;
  project?: string;
  title?: string;
}) => Promise<LinearGetTeamResult>;
  };
}

export declare const tools: SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84;
export type SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84Tools = SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84;
export default tools;
