// Generated by executor. Do not edit by hand.
// Source: mcp.context7.com (src_36fbe0ba-aedf-4cd9-88ff-6bebde47f69f)

type ComQueryDocsResultData = unknown | null;
type ComQueryDocsResultHeaders = {
  [key: string]: string;
};
type McpContext7ComQueryDocsResult = {
  data: ComQueryDocsResultData;
  error: ComQueryDocsResultData;
  headers: ComQueryDocsResultHeaders;
  status: null;
};

export interface SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69f {
  mcp: {
    context7: {
      com: {
        query_docs: (args: {
  libraryId: string;
  query: string;
}) => Promise<McpContext7ComQueryDocsResult>;
        resolve_library_id: (args: {
  libraryName: string;
  query: string;
}) => Promise<McpContext7ComQueryDocsResult>;
      };
    };
  };
}

export declare const tools: SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69f;
export type SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69fTools = SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69f;
export default tools;
