// Generated by executor. Do not edit by hand.
// Source: mcp.exa.ai (src_e5de4a36-ced8-4e44-8757-6b1e98d8b841)

type WebSearchExaResultData = unknown | null;

export interface SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841 {
  mcp: {
    exa: {
      ai: {
        web_search_exa: (args: {
  category?: "company" | "research paper" | "people";
  contextMaxCharacters?: number;
  livecrawl?: "fallback" | "preferred";
  numResults?: number;
  query: string;
  type?: "auto" | "fast";
}) => Promise<{
  data: WebSearchExaResultData;
  error: WebSearchExaResultData;
  headers: {
  [key: string]: string;
};
  status: null;
}>;
      };
    };
  };
}

export declare const tools: SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841;
export type SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841Tools = SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841;
export default tools;
