// Generated by executor. Do not edit by hand.
import type { SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69f } from "./sources/src_36fbe0ba-aedf-4cd9-88ff-6bebde47f69f";
import type { SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84 } from "./sources/src_9d2afca7-3234-440d-90ca-6365561e7e84";
import type { SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841 } from "./sources/src_e5de4a36-ced8-4e44-8757-6b1e98d8b841";

export type ExecutorSourceTools = SourceTools_src_36fbe0ba_aedf_4cd9_88ff_6bebde47f69f & SourceTools_src_9d2afca7_3234_440d_90ca_6365561e7e84 & SourceTools_src_e5de4a36_ced8_4e44_8757_6b1e98d8b841;

declare global {
  const tools: ExecutorSourceTools;
}

export declare const tools: ExecutorSourceTools;
export default tools;
